# This file is a derivative work of the Matlab implementation released
# alongside Chadwick and James, "Animating Fire with Sound," SIGGRAPH 2011.
# See https://www.cs.cornell.edu/projects/Sound/fire/ for the original.
#
# Original copyright notice (preserved per BSD 2-Clause):
#
# Copyright (c) 2011, Jeffrey Chadwick
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# - Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
"""Produce ``tests/golden_synthetic.json`` for the in-browser parity check.

The JS port reads this golden and runs ``BandwidthExtension.extendSignal`` on
the same input with the same phases, then reports the achieved peak/L2
errors. Spec section 4.2 calls for max abs error below 1e-6.

Run from the project root:

    python python/tools/generate_synthetic_golden.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent))

from bandwidth_extension import extend_signal  # noqa: E402
from deterministic_rng import DeterministicRng  # noqa: E402

ROOT = _HERE.parents[1]
OUT = ROOT / "tests" / "golden_synthetic.json"

FS = 44100.0
L = 4096
NFFT = 4096  # already a power of two, so nextpow2(L) == L
SEED = 42
ALPHA = 2.5
HALF_WIDTH = 500


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)

    # A short, smooth, mostly-low-frequency burst that exercises both the
    # in-band signal path and the high-frequency noise contribution.
    t = np.arange(L) / FS
    envelope = np.exp(-(((t - L / FS / 2) / 0.04) ** 2))
    p = (
        0.6 * envelope * np.sin(2.0 * np.pi * 60.0 * t)
        + 0.3 * envelope * np.sin(2.0 * np.pi * 130.0 * t)
        + 0.1 * envelope * np.sin(2.0 * np.pi * 250.0 * t)
    )

    rng = DeterministicRng(SEED)
    phases = 2.0 * np.pi * rng.random_array(NFFT)

    diag = extend_signal(
        p,
        fs=FS,
        alpha=ALPHA,
        half_width=HALF_WIDTH,
        phases_override=phases,
        return_diagnostics=True,
    )
    extended = diag["extended"]
    betas = diag["betas"]
    lowpass = diag["lowpass"]

    payload = {
        "_about": (
            "Parity golden for tests/validate.html. Generated by "
            "python/tools/generate_synthetic_golden.py. The JS port must "
            "reproduce 'expected_extended' from 'input' + 'phases' with the "
            "same params, within ~1e-6 max abs error."
        ),
        "params": {
            "fs": FS,
            "L": L,
            "NFFT": NFFT,
            "alpha": ALPHA,
            "half_width": HALF_WIDTH,
            "f_cutoff": 180.0,
            "fit_center": 180.0,
            "fit_width": 30.0,
            "blend_start": 165.0,
            "blend_end": 195.0,
            "noise_amplitude": 1.0,
            "seed": SEED,
            "nfft_per_window": None,
        },
        "input": p.tolist(),
        "phases": phases.tolist(),
        "expected_extended": extended.tolist(),
        "expected_betas": betas.tolist(),
        "expected_lowpass": lowpass.tolist(),
    }
    OUT.write_text(json.dumps(payload))
    size_kb = OUT.stat().st_size / 1024
    print(
        f"wrote {OUT.relative_to(ROOT)} ({size_kb:.1f} KB), "
        f"{len(extended)} samples, {len(betas)} betas"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
