# This file is a derivative work of the C++ implementation released
# alongside Chadwick and James, "Animating Fire with Sound," SIGGRAPH 2011.
# See https://www.cs.cornell.edu/projects/Sound/fire/ for the original.
#
# Original copyright notice (preserved per BSD 2-Clause):
#
# Copyright (c) 2011, Jeffrey Chadwick
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# - Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
"""Produce ``tests/golden_synthetic.json`` for the in-browser parity check.

Run from the project root:

    python python/tools/generate_synthetic_golden.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent))

from texture_synthesis import synthesize  # noqa: E402

ROOT = _HERE.parents[1]
OUT = ROOT / "tests" / "golden_synthetic.json"

FS = 44100.0


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)

    # Base: 4096-sample low-frequency burst (well below 200 Hz).
    base_n = 4097  # one above a power of 2 so pyramid construction is clean
    t = np.arange(base_n) / FS
    envelope = np.exp(-(((t - base_n / FS / 2) / 0.04) ** 2))
    base = (
        0.5 * envelope * np.sin(2.0 * np.pi * 90.0 * t)
        + 0.3 * envelope * np.sin(2.0 * np.pi * 140.0 * t)
    )

    # Training: 16385-sample pink-ish noise (deterministic seed).
    train_n = 16385
    rng = np.random.default_rng(7)
    white = rng.standard_normal(train_n)
    from scipy.signal import butter, filtfilt
    b, a = butter(2, 5000.0 / (FS / 2.0), btype="low")
    training = (0.4 * filtfilt(b, a, white)).astype(np.float64)

    # Synthesise with default-ish parameters (smaller pyramid for speed).
    params = {
        "fs": FS,
        "num_levels": 5,
        "window_hw": 4,
        "feature_hw": 3,
        "falloff": 0.0,
        "scale_cdf": True,
        "scaling_alpha": 1.0,
    }
    diag = synthesize(base, training, return_diagnostics=True, **params)
    output = diag["output"]

    payload = {
        "_about": (
            "Parity golden for tests/validate.html. Generated by "
            "python/tools/generate_synthetic_golden.py. The JS port must "
            "reproduce 'expected_output' from 'base' + 'training' with the "
            "same params, within ~1e-6 max abs error."
        ),
        "params": params,
        "base": base.tolist(),
        "training": training.tolist(),
        "expected_output": output.tolist(),
        "expected_scaling_per_window": diag["scaling_per_window"].tolist(),
    }
    OUT.write_text(json.dumps(payload))
    size_kb = OUT.stat().st_size / 1024
    print(
        f"wrote {OUT.relative_to(ROOT)} ({size_kb:.1f} KB), "
        f"{len(output)} samples, {len(diag['scaling_per_window'])} windows"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
